// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.healthResponse"
                        }
                    }
                }
            }
        },
        "/api/markets": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "List markets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.marketsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "PrivyToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Create market",
                "parameters": [
                    {
                        "description": "Create market payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/markets.CreateMarketRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/httpapi.marketResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/markets/{marketId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Markets"
                ],
                "summary": "Get market",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "marketId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.marketResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/orderbook/{marketId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market Data"
                ],
                "summary": "Get orderbook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "marketId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/matching.OrderbookSnapshot"
                        }
                    }
                }
            }
        },
        "/api/orders": {
            "post": {
                "security": [
                    {
                        "PrivyToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Place order",
                "parameters": [
                    {
                        "description": "Place order payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orders.PlaceOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/httpapi.placeOrderAcceptedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/orders/open/{marketId}": {
            "get": {
                "security": [
                    {
                        "PrivyToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get current user's open orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "marketId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.openOrdersResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/orders/{orderId}": {
            "delete": {
                "security": [
                    {
                        "PrivyToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Cancel order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "market_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/httpapi.cancelOrderAcceptedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/positions/{marketId}": {
            "get": {
                "security": [
                    {
                        "PrivyToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Positions"
                ],
                "summary": "Get current user's projected position",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "marketId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.positionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/price-history/{marketId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market Data"
                ],
                "summary": "Get price history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "marketId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1H|6H|1D|1W|1M|ALL",
                        "name": "range",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/matching.PriceHistory"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ready": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Readiness status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.readyResponse"
                        }
                    }
                }
            }
        },
        "/api/trades/{marketId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market Data"
                ],
                "summary": "Get recent trades",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market ID",
                        "name": "marketId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.tradesResponse"
                        }
                    }
                }
            }
        },
        "/api/wallet-account": {
            "get": {
                "security": [
                    {
                        "PrivyToken": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Positions"
                ],
                "summary": "Get current user's trading account balance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.walletAccountResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpapi.cancelOrderAcceptedResponse": {
            "type": "object",
            "properties": {
                "command_id": {
                    "type": "string"
                },
                "market_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                }
            }
        },
        "httpapi.errorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "httpapi.healthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "httpapi.marketResponse": {
            "type": "object",
            "properties": {
                "market": {
                    "$ref": "#/definitions/markets.Market"
                }
            }
        },
        "httpapi.marketsResponse": {
            "type": "object",
            "properties": {
                "markets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/markets.Market"
                    }
                }
            }
        },
        "httpapi.openOrdersResponse": {
            "type": "object",
            "properties": {
                "matching_enabled": {
                    "type": "boolean"
                },
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/matching.OpenOrder"
                    }
                }
            }
        },
        "httpapi.placeOrderAcceptedResponse": {
            "type": "object",
            "properties": {
                "command_id": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "market_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                }
            }
        },
        "httpapi.positionResponse": {
            "type": "object",
            "properties": {
                "collateral_free_units": {
                    "type": "string"
                },
                "collateral_locked_units": {
                    "type": "string"
                },
                "market_id": {
                    "type": "string"
                },
                "no_free_lots": {
                    "type": "string"
                },
                "no_locked_lots": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                },
                "yes_free_lots": {
                    "type": "string"
                },
                "yes_locked_lots": {
                    "type": "string"
                }
            }
        },
        "httpapi.readyResponse": {
            "type": "object",
            "properties": {
                "gateway_write_ready": {
                    "type": "boolean"
                },
                "matcher": {
                    "type": "string"
                },
                "pusher": {
                    "type": "string"
                },
                "settlement": {
                    "type": "string"
                },
                "writer": {
                    "type": "string"
                }
            }
        },
        "httpapi.tradesResponse": {
            "type": "object",
            "properties": {
                "matching_enabled": {
                    "type": "boolean"
                },
                "trades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/matching.Trade"
                    }
                }
            }
        },
        "httpapi.walletAccountResponse": {
            "type": "object",
            "properties": {
                "collateral_free_units": {
                    "type": "string"
                },
                "collateral_total_units": {
                    "type": "string"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "markets.CreateMarketRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "close_time": {
                    "type": "string"
                },
                "collateral_mint": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "metadata_url": {
                    "type": "string"
                },
                "resolution": {
                    "$ref": "#/definitions/markets.ResolutionConfig"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "markets.Market": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "close_time": {
                    "type": "string"
                },
                "collateral_mint": {
                    "type": "string"
                },
                "collateral_vault": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "market_id": {
                    "type": "string",
                    "example": "0"
                },
                "market_pda": {
                    "type": "string"
                },
                "metadata_url": {
                    "type": "string"
                },
                "no_mint": {
                    "type": "string"
                },
                "outcome": {
                    "$ref": "#/definitions/markets.MarketOutcome"
                },
                "resolution": {
                    "$ref": "#/definitions/markets.ResolutionConfig"
                },
                "resolved_at": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/markets.MarketStatus"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "yes_mint": {
                    "type": "string"
                }
            }
        },
        "markets.MarketOutcome": {
            "type": "string",
            "enum": [
                "yes",
                "no",
                "undecided"
            ],
            "x-enum-varnames": [
                "MarketOutcomeYes",
                "MarketOutcomeNo",
                "MarketOutcomeUndecided"
            ]
        },
        "markets.MarketStatus": {
            "type": "string",
            "enum": [
                "open",
                "resolved"
            ],
            "x-enum-varnames": [
                "MarketStatusOpen",
                "MarketStatusResolved"
            ]
        },
        "markets.OracleCondition": {
            "type": "string",
            "enum": [
                "gt",
                "gte",
                "lt",
                "lte"
            ],
            "x-enum-varnames": [
                "OracleConditionGT",
                "OracleConditionGTE",
                "OracleConditionLT",
                "OracleConditionLTE"
            ]
        },
        "markets.ResolutionConfig": {
            "type": "object",
            "properties": {
                "authority": {
                    "type": "string"
                },
                "mode": {
                    "$ref": "#/definitions/markets.ResolutionMode"
                },
                "oracle_condition": {
                    "$ref": "#/definitions/markets.OracleCondition"
                },
                "oracle_feed": {
                    "type": "string"
                },
                "oracle_observation_time": {
                    "type": "string"
                },
                "oracle_target_price": {
                    "type": "integer"
                }
            }
        },
        "markets.ResolutionMode": {
            "type": "string",
            "enum": [
                "creator",
                "pyth"
            ],
            "x-enum-varnames": [
                "ResolutionModeCreator",
                "ResolutionModePyth"
            ]
        },
        "matching.OpenOrder": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "outcome": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                },
                "side": {
                    "type": "string"
                }
            }
        },
        "matching.OrderLevel": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "string"
                },
                "total_volume": {
                    "type": "string"
                }
            }
        },
        "matching.OrderbookSnapshot": {
            "type": "object",
            "properties": {
                "asks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/matching.OrderLevel"
                    }
                },
                "best_ask_price": {
                    "type": "string"
                },
                "best_bid_price": {
                    "type": "string"
                },
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/matching.OrderLevel"
                    }
                },
                "matching_enabled": {
                    "type": "boolean"
                }
            }
        },
        "matching.PriceHistory": {
            "type": "object",
            "properties": {
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/matching.PricePoint"
                    }
                },
                "range": {
                    "$ref": "#/definitions/matching.PriceHistoryRange"
                }
            }
        },
        "matching.PriceHistoryRange": {
            "type": "string",
            "enum": [
                "1H",
                "6H",
                "1D",
                "1W",
                "1M",
                "ALL"
            ],
            "x-enum-varnames": [
                "PriceHistoryRange1H",
                "PriceHistoryRange6H",
                "PriceHistoryRange1D",
                "PriceHistoryRange1W",
                "PriceHistoryRange1M",
                "PriceHistoryRangeAll"
            ]
        },
        "matching.PricePoint": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "matching.Trade": {
            "type": "object",
            "properties": {
                "executed_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                }
            }
        },
        "orders.PlaceOrderRequest": {
            "type": "object",
            "properties": {
                "expire_time": {
                    "description": "Unix秒级时间戳 (0=GTC)",
                    "type": "integer"
                },
                "market_id": {
                    "description": "市场ID",
                    "type": "string",
                    "example": "0"
                },
                "nonce": {
                    "description": "防碰撞nonce (42位时间戳+22位随机数)",
                    "type": "string",
                    "example": "0"
                },
                "order_type": {
                    "description": "\"limit\" | \"market\"",
                    "type": "string"
                },
                "original_action": {
                    "description": "用户原始动作: buy | sell",
                    "type": "string"
                },
                "original_outcome": {
                    "description": "用户原始标的: yes | no",
                    "type": "string"
                },
                "original_price_tick": {
                    "description": "用户原始价格/滑点边界",
                    "type": "integer"
                },
                "price_tick": {
                    "description": "归一化后的 1-99",
                    "type": "integer"
                },
                "qty_lots": {
                    "description": "份额 (乘100后的整数，市价买入为0)",
                    "type": "integer"
                },
                "side": {
                    "description": "归一化后的 \"buy\" | \"sell\" (只面向 YES)",
                    "type": "string"
                },
                "signature": {
                    "description": "base64 Ed25519签名 (对Keccak256(Borsh(Intent))签名)",
                    "type": "string"
                },
                "spend_amount": {
                    "description": "金额 (乘100后的整数，仅市价买入有值)",
                    "type": "integer"
                },
                "wallet_address": {
                    "description": "用户钱包地址 (base58)",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "PrivyToken": {
            "type": "apiKey",
            "name": "privy-id-token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "BlinkPredict Banckend API",
	Description:      "BlinkPredict backend API documentation. Import /api/openapi.json into Postman or FoxAPI.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
